kind: pipeline
type: docker
name: default

workspace:
  base: /skyffxi

platform:
  os: linux
  arch: amd64

steps:
- name: build-executables
  image: ubuntu:18.04
  environment:
    CC: /usr/bin/clang
    CXX: /usr/bin/clang++
  commands:
  - apt update
  - apt install -y software-properties-common clang cmake libmariadb-dev-compat libluajit-5.1-dev libzmq3-dev zlib1g-dev libssl-dev
  - cmake .
  - make -j $(nproc)
  - ls -la

- name: testing
  image: ubuntu:18.04
  commands:
  - ls -la
  depends_on:
  - build-executables

# - name: package-topaz-connect
#   image: plugins/docker
#   settings:
#     repo: skyffxi/topaz-connect
#     dockerfile: docker/topaz-connect/Dockerfile
#     username:
#       from_secret: docker-username
#     password:
#       from_secret: docker-password
#   depends_on:
#   - build-executables
